### ISSUE TITLE
(edge case) Multiple logins issue

### ISSUE THREAD

**Issue by etipton** [ryanjohns/passmaster#5] opened 2015-08-12 15:04 UTC
@ryanjohns just documenting this one in case you have any suggestions for the best fix --

MFA doesn't work if you have multiple logins and you try using the same browser for all of them... I think because of the way the code sets one permanent _client_id session cookie (maybe?)

I forked the repo and maybe one day I can dig in to try and fix :)

Meanwhile if you have any insight let me know.

**Comment by ryanjohns** [comment] 2015-08-12 21:57
Yeah, that sounds like the cause. I'll take a look soon as I can't remember all the flows off the top of my head. Thanks!

**Comment by etipton** [comment] 2015-08-15 08:40
To recreate the underlying issue:

1. Clear all cookies for 127.0.0.1 (or whatever development domain used)
2. Create a new user and enable MFA.
3. Click the logout button.
4. Try to repeat number 2 with a second new user - enabling MFA will fail when attempting to enter the code.

**Comment by ryanjohns** [comment] 2015-08-16 20:46
Thanks for tracking this down! It has been fixed via b59a87c33dda3d4bb500804d26b0df0aa2e57678.

**Closed by ryanjohns** 2015-08-16 20:46 UTC

**Comment by etipton** [comment] 2015-08-16 23:15
Awesome! Thanks so much.

**Comment by etipton** [comment] 2015-08-16 23:32
Just tested in production -- working perfectly for me.

**Comment by ryanjohns** [comment] 2015-08-17 00:24
Excellent!
